FROM docker.io/golang:1.25.7 AS daemon-builder
WORKDIR /go/src/github.com/k8snetworkplumbingwg/linuxptp-daemon
ENV GOMAXPROCS=16

RUN git clone -b main https://github.com/k8snetworkplumbingwg/linuxptp-daemon.git  /go/src/github.com/k8snetworkplumbingwg/linuxptp-daemon

RUN make clean && make -j 16

FROM quay.io/centos/centos:stream9
COPY --from=daemon-builder /go/src/github.com/k8snetworkplumbingwg/linuxptp-daemon/bin/cloud-event-proxy /usr/local/bin/
LABEL io.k8s.display-name="Cloud Event Proxy v2" \
      io.k8s.description="Cloud Event Proxy (v2) built from linuxptp-daemon, run as an in-daemon event proxy sidecar." \
      io.openshift.tags="openshift" \
      maintainer="PTP Team <ptp-dev@redhat.com>"

CMD ["/usr/local/bin/cloud-event-proxy"]
