FROM quay.io/centos/centos:stream9

#RUN yum install -y go dlv
#RUN yum -y update && yum -y update glibc && yum --setopt=skip_missing_names_on_install=False -y install 


RUN yum install -y gpsd-minimal glibc gpsd-minimal-clients linuxptp ethtool hwdata synce4l  && yum clean all

# Create symlinks for executables to match references
RUN ln -s /usr/bin/gpspipe /usr/local/bin/gpspipe
RUN ln -s /usr/sbin/gpsd /usr/local/sbin/gpsd
RUN ln -s /usr/bin/ubxtool /usr/local/bin/ubxtool
