//go:build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v2alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Behavior) DeepCopyInto(out *Behavior) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]SourceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Behavior.
func (in *Behavior) DeepCopy() *Behavior {
	if in == nil {
		return nil
	}
	out := new(Behavior)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClockChain) DeepCopyInto(out *ClockChain) {
	*out = *in
	if in.CommonDefinitions != nil {
		in, out := &in.CommonDefinitions, &out.CommonDefinitions
		*out = new(CommonDefinitions)
		(*in).DeepCopyInto(*out)
	}
	if in.Structure != nil {
		in, out := &in.Structure, &out.Structure
		*out = make([]Subsystem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Behavior != nil {
		in, out := &in.Behavior, &out.Behavior
		*out = new(Behavior)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClockChain.
func (in *ClockChain) DeepCopy() *ClockChain {
	if in == nil {
		return nil
	}
	out := new(ClockChain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonDefinitions) DeepCopyInto(out *CommonDefinitions) {
	*out = *in
	if in.ESyncDefinitions != nil {
		in, out := &in.ESyncDefinitions, &out.ESyncDefinitions
		*out = make([]ESyncDefinition, len(*in))
		copy(*out, *in)
	}
	if in.RefSyncDefinitions != nil {
		in, out := &in.RefSyncDefinitions, &out.RefSyncDefinitions
		*out = make([]RefSyncDefinition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonDefinitions.
func (in *CommonDefinitions) DeepCopy() *CommonDefinitions {
	if in == nil {
		return nil
	}
	out := new(CommonDefinitions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make([]SourceState, len(*in))
		copy(*out, *in)
	}
	if in.DesiredStates != nil {
		in, out := &in.DesiredStates, &out.DesiredStates
		*out = make([]DesiredState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPLL) DeepCopyInto(out *DPLL) {
	*out = *in
	if in.HoldoverParameters != nil {
		in, out := &in.HoldoverParameters, &out.HoldoverParameters
		*out = new(HoldoverParameters)
		**out = **in
	}
	if in.PhaseInputs != nil {
		in, out := &in.PhaseInputs, &out.PhaseInputs
		*out = make(map[string]PinConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.PhaseOutputs != nil {
		in, out := &in.PhaseOutputs, &out.PhaseOutputs
		*out = make(map[string]PinConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.FrequencyInputs != nil {
		in, out := &in.FrequencyInputs, &out.FrequencyInputs
		*out = make(map[string]PinConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.FrequencyOutputs != nil {
		in, out := &in.FrequencyOutputs, &out.FrequencyOutputs
		*out = make(map[string]PinConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPLL.
func (in *DPLL) DeepCopy() *DPLL {
	if in == nil {
		return nil
	}
	out := new(DPLL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPLLDesiredState) DeepCopyInto(out *DPLLDesiredState) {
	*out = *in
	if in.EEC != nil {
		in, out := &in.EEC, &out.EEC
		*out = new(PinState)
		(*in).DeepCopyInto(*out)
	}
	if in.PPS != nil {
		in, out := &in.PPS, &out.PPS
		*out = new(PinState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPLLDesiredState.
func (in *DPLLDesiredState) DeepCopy() *DPLLDesiredState {
	if in == nil {
		return nil
	}
	out := new(DPLLDesiredState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesiredState) DeepCopyInto(out *DesiredState) {
	*out = *in
	if in.DPLL != nil {
		in, out := &in.DPLL, &out.DPLL
		*out = new(DPLLDesiredState)
		(*in).DeepCopyInto(*out)
	}
	if in.SysFS != nil {
		in, out := &in.SysFS, &out.SysFS
		*out = new(SysFSDesiredState)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesiredState.
func (in *DesiredState) DeepCopy() *DesiredState {
	if in == nil {
		return nil
	}
	out := new(DesiredState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ESyncConfig) DeepCopyInto(out *ESyncConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ESyncConfig.
func (in *ESyncConfig) DeepCopy() *ESyncConfig {
	if in == nil {
		return nil
	}
	out := new(ESyncConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ESyncDefinition) DeepCopyInto(out *ESyncDefinition) {
	*out = *in
	out.ESyncConfig = in.ESyncConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ESyncDefinition.
func (in *ESyncDefinition) DeepCopy() *ESyncDefinition {
	if in == nil {
		return nil
	}
	out := new(ESyncDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ethernet) DeepCopyInto(out *Ethernet) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ethernet.
func (in *Ethernet) DeepCopy() *Ethernet {
	if in == nil {
		return nil
	}
	out := new(Ethernet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardwareConfig) DeepCopyInto(out *HardwareConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardwareConfig.
func (in *HardwareConfig) DeepCopy() *HardwareConfig {
	if in == nil {
		return nil
	}
	out := new(HardwareConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HardwareConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardwareConfigList) DeepCopyInto(out *HardwareConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HardwareConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardwareConfigList.
func (in *HardwareConfigList) DeepCopy() *HardwareConfigList {
	if in == nil {
		return nil
	}
	out := new(HardwareConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HardwareConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardwareConfigSpec) DeepCopyInto(out *HardwareConfigSpec) {
	*out = *in
	in.Profile.DeepCopyInto(&out.Profile)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardwareConfigSpec.
func (in *HardwareConfigSpec) DeepCopy() *HardwareConfigSpec {
	if in == nil {
		return nil
	}
	out := new(HardwareConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardwareConfigStatus) DeepCopyInto(out *HardwareConfigStatus) {
	*out = *in
	if in.MatchedNodes != nil {
		in, out := &in.MatchedNodes, &out.MatchedNodes
		*out = make([]MatchedNode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardwareConfigStatus.
func (in *HardwareConfigStatus) DeepCopy() *HardwareConfigStatus {
	if in == nil {
		return nil
	}
	out := new(HardwareConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardwareOptionsConfig) DeepCopyInto(out *HardwareOptionsConfig) {
	*out = *in
	out.PluginInfo = in.PluginInfo
	if in.SpecificDefaults != nil {
		in, out := &in.SpecificDefaults, &out.SpecificDefaults
		*out = make(PluginSpecificDefaults, len(*in))
		for key, val := range *in {
			var outVal *PinOverrides
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(PinOverrides)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardwareOptionsConfig.
func (in *HardwareOptionsConfig) DeepCopy() *HardwareOptionsConfig {
	if in == nil {
		return nil
	}
	out := new(HardwareOptionsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardwareProfile) DeepCopyInto(out *HardwareProfile) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ClockChain != nil {
		in, out := &in.ClockChain, &out.ClockChain
		*out = new(ClockChain)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardwareProfile.
func (in *HardwareProfile) DeepCopy() *HardwareProfile {
	if in == nil {
		return nil
	}
	out := new(HardwareProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HoldoverParameters) DeepCopyInto(out *HoldoverParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HoldoverParameters.
func (in *HoldoverParameters) DeepCopy() *HoldoverParameters {
	if in == nil {
		return nil
	}
	out := new(HoldoverParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchedNode) DeepCopyInto(out *MatchedNode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchedNode.
func (in *MatchedNode) DeepCopy() *MatchedNode {
	if in == nil {
		return nil
	}
	out := new(MatchedNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhaseAdjustment) DeepCopyInto(out *PhaseAdjustment) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhaseAdjustment.
func (in *PhaseAdjustment) DeepCopy() *PhaseAdjustment {
	if in == nil {
		return nil
	}
	out := new(PhaseAdjustment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinConfig) DeepCopyInto(out *PinConfig) {
	*out = *in
	if in.PhaseAdjustment != nil {
		in, out := &in.PhaseAdjustment, &out.PhaseAdjustment
		*out = new(PhaseAdjustment)
		(*in).DeepCopyInto(*out)
	}
	if in.Frequency != nil {
		in, out := &in.Frequency, &out.Frequency
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinConfig.
func (in *PinConfig) DeepCopy() *PinConfig {
	if in == nil {
		return nil
	}
	out := new(PinConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinOverrides) DeepCopyInto(out *PinOverrides) {
	*out = *in
	if in.EEC != nil {
		in, out := &in.EEC, &out.EEC
		*out = new(PluginPinDefaults)
		(*in).DeepCopyInto(*out)
	}
	if in.PPS != nil {
		in, out := &in.PPS, &out.PPS
		*out = new(PluginPinDefaults)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinOverrides.
func (in *PinOverrides) DeepCopy() *PinOverrides {
	if in == nil {
		return nil
	}
	out := new(PinOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinState) DeepCopyInto(out *PinState) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinState.
func (in *PinState) DeepCopy() *PinState {
	if in == nil {
		return nil
	}
	out := new(PinState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginInfo) DeepCopyInto(out *PluginInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginInfo.
func (in *PluginInfo) DeepCopy() *PluginInfo {
	if in == nil {
		return nil
	}
	out := new(PluginInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginPinDefaults) DeepCopyInto(out *PluginPinDefaults) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginPinDefaults.
func (in *PluginPinDefaults) DeepCopy() *PluginPinDefaults {
	if in == nil {
		return nil
	}
	out := new(PluginPinDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in PluginSpecificDefaults) DeepCopyInto(out *PluginSpecificDefaults) {
	{
		in := &in
		*out = make(PluginSpecificDefaults, len(*in))
		for key, val := range *in {
			var outVal *PinOverrides
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(PinOverrides)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginSpecificDefaults.
func (in PluginSpecificDefaults) DeepCopy() PluginSpecificDefaults {
	if in == nil {
		return nil
	}
	out := new(PluginSpecificDefaults)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RefSyncDefinition) DeepCopyInto(out *RefSyncDefinition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RefSyncDefinition.
func (in *RefSyncDefinition) DeepCopy() *RefSyncDefinition {
	if in == nil {
		return nil
	}
	out := new(RefSyncDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceConfig) DeepCopyInto(out *SourceConfig) {
	*out = *in
	if in.PTPTimeReceivers != nil {
		in, out := &in.PTPTimeReceivers, &out.PTPTimeReceivers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceConfig.
func (in *SourceConfig) DeepCopy() *SourceConfig {
	if in == nil {
		return nil
	}
	out := new(SourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceState) DeepCopyInto(out *SourceState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceState.
func (in *SourceState) DeepCopy() *SourceState {
	if in == nil {
		return nil
	}
	out := new(SourceState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subsystem) DeepCopyInto(out *Subsystem) {
	*out = *in
	in.DPLL.DeepCopyInto(&out.DPLL)
	if in.Ethernet != nil {
		in, out := &in.Ethernet, &out.Ethernet
		*out = make([]Ethernet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subsystem.
func (in *Subsystem) DeepCopy() *Subsystem {
	if in == nil {
		return nil
	}
	out := new(Subsystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SysFSDesiredState) DeepCopyInto(out *SysFSDesiredState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SysFSDesiredState.
func (in *SysFSDesiredState) DeepCopy() *SysFSDesiredState {
	if in == nil {
		return nil
	}
	out := new(SysFSDesiredState)
	in.DeepCopyInto(out)
	return out
}
