FROM registry.svc.ci.openshift.org/ocp/builder:golang-1.12 AS builder
WORKDIR /go/src/github.com/openshift/ptp-operator
COPY . .

FROM registry.svc.ci.openshift.org/ocp/4.0:cli
LABEL io.k8s.display-name="ptp-operator-must-gather" \
      io.k8s.description="This is a PTP must-gather image that collectes PTP operator related resources."
COPY --from=builder /go/src/github.com/openshift/ptp-operator/must-gather/collection-scripts/* /usr/bin/

ENTRYPOINT /usr/bin/gather
