---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ptp-openshift-io-v1-ptpconfig
  failurePolicy: Fail
  name: vptpconfig.kb.io
  rules:
  - apiGroups:
    - ptp.openshift.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ptpconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ptp-openshift-io-v1-ptpoperatorconfig
  failurePolicy: Fail
  name: vptpoperatorconfig.kb.io
  rules:
  - apiGroups:
    - ptp.openshift.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ptpoperatorconfigs
  sideEffects: None
