# permissions for end users to view nodeptpdevices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeptpdevice-viewer-role
rules:
- apiGroups:
  - ptp.openshift.io
  resources:
  - nodeptpdevices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ptp.openshift.io
  resources:
  - nodeptpdevices/status
  verbs:
  - get
