# permissions for end users to edit ptpconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ptpconfig-editor-role
rules:
- apiGroups:
  - ptp.openshift.io
  resources:
  - ptpconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ptp.openshift.io
  resources:
  - ptpconfigs/status
  verbs:
  - get
