# permissions for end users to view ptpconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ptpconfig-viewer-role
rules:
- apiGroups:
  - ptp.openshift.io
  resources:
  - ptpconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ptp.openshift.io
  resources:
  - ptpconfigs/status
  verbs:
  - get
