# permissions for end users to view ptpoperatorconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ptpoperatorconfig-viewer-role
rules:
- apiGroups:
  - ptp.openshift.io
  resources:
  - ptpoperatorconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ptp.openshift.io
  resources:
  - ptpoperatorconfigs/status
  verbs:
  - get
