# permissions for end users to edit ptpoperatorconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ptpoperatorconfig-editor-role
rules:
- apiGroups:
  - ptp.openshift.io
  resources:
  - ptpoperatorconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ptp.openshift.io
  resources:
  - ptpoperatorconfigs/status
  verbs:
  - get
