
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ptp.openshift.io
  resources:
  - ptpconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ptp.openshift.io
  resources:
  - ptpconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - ptp.openshift.io
  resources:
  - ptpconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ptp.openshift.io
  resources:
  - ptpoperatorconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ptp.openshift.io
  resources:
  - ptpoperatorconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - ptp.openshift.io
  resources:
  - ptpoperatorconfigs/status
  verbs:
  - get
  - patch
  - update
