---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linuxptp-daemon
rules:
- apiGroups: ["ptp.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: linuxptp-daemon
roleRef:
  kind: ClusterRole
  name: linuxptp-daemon
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: linuxptp-daemon
  namespace: openshift-ptp
