apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ptpoperatorconfigs.ptp.openshift.io
spec:
  group: ptp.openshift.io
  names:
    kind: PtpOperatorConfig
    listKind: PtpOperatorConfigList
    plural: ptpoperatorconfigs
    singular: ptpoperatorconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: PtpOperatorConfig is the Schema for the ptpoperatorconfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PtpOperatorConfigSpec defines the desired state of PtpOperatorConfig
            properties:
              daemonNodeSelector:
                additionalProperties:
                  type: string
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "operator-sdk generate k8s" to regenerate code after
                  modifying this file Add custom validation using kubebuilder tags:
                  https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                type: object
              ptpEventConfig:
                description: PtpEventConfig defines the desired state of event framework
                properties:
                  enableEventPublisher:
                    description: EnableEventPublisher will deploy event proxy as a
                      sidecar
                    type: boolean
                  holdOverTimeout:
                    description: clock state to stay in holdover state in secs
                    format: int64
                    type: integer
                  maxOffsetThreshold:
                    description: max offset in nano secs
                    format: int64
                    type: integer
                  minOffsetThreshold:
                    description: min offset in nano secs
                    format: int64
                    type: integer
                  transportHost:
                    description: transportHost address for event messages
                    type: string
                type: object
            required:
            - daemonNodeSelector
            type: object
          status:
            description: PtpOperatorConfigStatus defines the observed state of PtpOperatorConfig
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
