apiVersion: ptp.openshift.io/v1
kind: PtpConfig
metadata:
  name: example-ptpconfig
spec:
  profile:
  - name: "profile1"
    interface: "ens787f1"
    ptp4lOpts: "-s -2"
    phc2sysOpts: "-a -r"
  recommend:
  - profile: "profile1"
    priority: 4
    match:
    - nodeName: "node.example.com"
      nodeLabel: "node-role.kubernetes.io/worker="
