---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "false"
  labels:
    app: linuxptp-daemon
  name:  ptp-event-publisher-service-{{.NodeName}}
  namespace: openshift-ptp
spec:
  clusterIP: None
  selector:
    app: linuxptp-daemon
    nodeName: {{.NodeName}}
  ports:
    - name: publisher-port
      port: 9043
  sessionAffinity: None
  type: ClusterIP
