name: Deploy Daemon Images to GHCR
env:
  DOTNET_VERSION: '6.0.x'
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Daemon Image'
            run: |
              make daemon-image
              make daemon-push

